
# make env variable
SHELL=/bin/sh
CC=gcc
MAKE=make

# project variable
MAKE_DIR=.
SRC_DIR=$(MAKE_DIR)/src
OBJ_DIR=$(MAKE_DIR)/obj
LIB_DIR=$(MAKE_DIR)/lib
INC_DIR=$(MAKE_DIR)/include
DBG_DIR=$(MAKE_DIR)/debug
RLS_DIR=$(MAKE_DIR)/release
EXEC_DIR=$(MAKE_DIR)

# build variable
INCLUDE=-I$(INC_DIR)
LIB=-L$(LIB_DIR) -ladd
EXEC=automk

vpath %.h $(INC_DIR)
vpath %.c $(SRC_DIR)
vpath %.o $(OBJ_DIR)
vpath %.d $(OBJ_DIR)

SRC_TMP=












